[package]
name = "anni-vgmdb"
version = "0.1.0"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls"]

[dev-dependencies]
tokio = { version = "1.5.0", features = ["full"] }